services:
  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    image: subwate/spring-app:latest
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_ENABLED=false

  spring-app-develop:
    build:
      context: .
      dockerfile: dockerfile
    image: subwate/spring-app-develop:latest
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_ENABLED=true