spring:
  application:
    name: subwate-backend
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:true}
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
